export * from "./about/About"
export * from "./events/Events"
export * from "./home/Home"
export * from "./read/Read"
export * from "./sermons/Sermons"
export * from "./login/Login"
export * from "./signUp/SignUp"
export * from "./testimonies/Testimonies"